2023-03-16 11:50:07,545 automl_forecast main.py main set_logger INFO: logger 세팅
2023-03-16 11:50:07,546 automl_forecast input_data.py input_data read_data INFO: csv 데이터 불러오기
2023-03-16 11:50:07,546 automl_forecast input_data.py input_data read_data INFO: storage/data/stallion.csv
2023-03-16 11:50:07,589 automl_forecast input_data.py input_data read_data INFO: 변수 분리 시작
2023-03-16 11:50:07,592 automl_forecast input_data.py input_data reduce_mem_usage INFO: 데이터 구성: 21000 행, 26열
2023-03-16 11:50:07,593 automl_forecast input_data.py input_data reduce_mem_usage INFO: Memory usage of dataframe is 4.17MB
2023-03-16 11:50:07,610 automl_forecast input_data.py input_data reduce_mem_usage INFO: Memory usage after optimization is: 0.91MB
2023-03-16 11:50:07,611 automl_forecast input_data.py input_data reduce_mem_usage INFO: Decreased by 78.2%
2023-03-16 11:50:07,612 automl_forecast preprocess.py preprocess na_preprocess INFO: 결측치 처리
2023-03-16 11:50:07,612 automl_forecast preprocess.py preprocess na_preprocess ERROR: 결측치 처리에 문제가 발생하였습니다
Traceback (most recent call last):
  File "C:\Users\dpapf\Desktop\automl_forecast\process\preprocess.py", line 53, in na_preprocess
    obj_data = df.loc[:, obj_var]
NameError: name 'obj_var' is not defined
2023-03-16 11:50:07,612 automl_forecast preprocess.py preprocess na_preprocess INFO: 결측치 처리 이후 데이터 구성: 21000 행, 26열
2023-03-16 11:50:07,612 automl_forecast preprocess.py preprocess tds_preprocess INFO: 전처리를 위한 target, date, store 분리
2023-03-16 11:50:07,614 automl_forecast preprocess.py preprocess standardize INFO: 정규화 진행
2023-03-16 11:50:07,672 automl_forecast preprocess.py preprocess label_encoder INFO: 라벨 인코딩 진행
2023-03-16 11:50:07,675 automl_forecast preprocess.py preprocess get_df INFO: 전처리 완료
2023-03-16 11:50:07,676 automl_forecast preprocess.py preprocess get_df INFO: 

2023-03-16 11:50:07,676 automl_forecast preprocess.py preprocess get_df INFO:    avg_max_temp  price_regular  price_actual  discount  discount_in_percent  \
0     -0.696963      -0.413455     -0.337471 -0.328691            -0.213089   
1     -0.531769       0.586046      0.584706  0.218970             0.252862   
2     -1.609464      -0.264188     -0.119687 -0.430163            -0.498605   
3     -0.818892      -0.403211     -0.313651 -0.353452            -0.274591   
4     -1.141414      -0.182238     -0.100971 -0.253193            -0.165842   

   industry_volume  soda_volume  avg_population_2017  \
0        -0.815995    -1.697382            -1.072907   
1        -0.815995    -1.697382            -1.089462   
2        -0.815995    -1.697382             0.188255   
3        -0.815995    -1.697382            -0.978834   
4        -0.815995    -1.697382             2.151600   

   avg_yearly_household_income_2017  easter_day  good_friday  new_year  \
0                         -0.376197   -0.301511    -0.301511  3.316625   
1                         -1.077449   -0.301511    -0.301511  3.316625   
2                          1.345580   -0.301511    -0.301511  3.316625   
3                         -1.004049   -0.301511    -0.301511  3.316625   
4                          0.632246   -0.301511    -0.301511  3.316625   

   christmas  labor_day  independence_day  revolution_day_memorial  \
0  -0.301511  -0.301511         -0.301511                -0.301511   
1  -0.301511  -0.301511         -0.301511                -0.301511   
2  -0.301511  -0.301511         -0.301511                -0.301511   
3  -0.301511  -0.301511         -0.301511                -0.301511   
4  -0.301511  -0.301511         -0.301511                -0.301511   

   regional_games  fifa_u_17_world_cup  football_gold_cup  beer_capital  \
0       -0.130189                  0.0                0.0     -0.301511   
1       -0.130189                  0.0                0.0     -0.301511   
2       -0.130189                  0.0                0.0     -0.301511   
3       -0.130189                  0.0                0.0     -0.301511   
4       -0.130189                  0.0                0.0     -0.301511   

   music_fest  timeseries     volume        date     sku     agency  
0   -0.301511   -1.727109   52.28125  2013-01-01  SKU_01  Agency_22  
1   -0.301511   -1.677622    0.00000  2013-01-01  SKU_04  Agency_37  
2   -0.301511   -1.638032  813.00000  2013-01-01  SKU_03  Agency_59  
3   -0.301511   -1.588545  316.50000  2013-01-01  SKU_01  Agency_11  
4   -0.301511   -1.509365  421.00000  2013-01-01  SKU_05  Agency_05  
2023-03-16 11:50:07,691 automl_forecast preprocess.py preprocess ts_preprocess INFO: 시계열용 전처리 진행
2023-03-16 11:50:09,006 automl_forecast preprocess.py preprocess ts_preprocess INFO: 시계열 전처리 후 df
2023-03-16 11:50:09,006 automl_forecast preprocess.py preprocess ts_preprocess INFO:    avg_max_temp  price_regular  price_actual  discount  discount_in_percent  \
0     -0.696963      -0.413455     -0.337471 -0.328691            -0.213089   
1      0.176207      -0.413455     -0.337471 -0.328205            -0.212274   
2      0.203739      -0.360773     -0.281323 -0.318738            -0.217162   
3      0.962846      -0.316871     -0.233683 -0.305872            -0.210645   
4      0.892048      -0.299310     -0.214967 -0.303444            -0.213903   

   industry_volume  soda_volume  avg_population_2017  \
0        -0.815995    -1.697382            -1.072907   
1        -1.780953    -1.243094            -1.072907   
2        -0.550900     0.523917            -1.072907   
3        -0.183385    -0.167437            -1.072907   
4         0.124586     0.168964            -1.072907   

   avg_yearly_household_income_2017  easter_day  good_friday  new_year  \
0                         -0.376197   -0.301511    -0.301511  3.316625   
1                         -0.376197   -0.301511    -0.301511 -0.301511   
2                         -0.376197    3.316625     3.316625 -0.301511   
3                         -0.376197   -0.301511    -0.301511 -0.301511   
4                         -0.376197   -0.301511    -0.301511 -0.301511   

   christmas  labor_day  independence_day  revolution_day_memorial  \
0  -0.301511  -0.301511         -0.301511                -0.301511   
1  -0.301511  -0.301511         -0.301511                -0.301511   
2  -0.301511  -0.301511         -0.301511                -0.301511   
3  -0.301511  -0.301511         -0.301511                -0.301511   
4  -0.301511   3.316625         -0.301511                -0.301511   

   regional_games  fifa_u_17_world_cup  football_gold_cup  beer_capital  \
0       -0.130189                  0.0                0.0     -0.301511   
1       -0.130189                  0.0                0.0     -0.301511   
2       -0.130189                  0.0                0.0     -0.301511   
3       -0.130189                  0.0                0.0     -0.301511   
4       -0.130189                  0.0                0.0     -0.301511   

   music_fest  timeseries    volume       date     sku     agency  time_idx  \
0   -0.301511   -1.727109  52.28125 2013-01-01  SKU_01  Agency_22         0   
1   -0.301511   -1.727109  62.53125 2013-02-01  SKU_01  Agency_22         1   
2    3.316625   -1.727109  74.18750 2013-03-01  SKU_01  Agency_22         2   
3   -0.301511   -1.727109  89.43750 2013-04-01  SKU_01  Agency_22         3   
4   -0.301511   -1.727109  79.18750 2013-05-01  SKU_01  Agency_22         4   

  month  
0     1  
1     2  
2     3  
3     4  
4     5  
2023-03-16 11:50:09,022 automl_forecast modeling.py modeling ari_fit_predict INFO: arima 데이터 준비
2023-03-16 11:50:09,022 automl_forecast modeling.py modeling ari_fit_predict INFO: arima 모델링 시작
2023-03-16 11:53:20,744 automl_forecast modeling.py modeling ets_fit_predict INFO: ets 데이터 준비
2023-03-16 11:53:20,822 automl_forecast modeling.py modeling ets_fit_predict ERROR: ets 모델링 도중 문제가 발생하였습니다.
Traceback (most recent call last):
  File "C:\Users\dpapf\Desktop\automl_forecast\process\modeling.py", line 241, in ets_fit_predict
    ets = Holt(ets_train['y'].values, exponential=True, initialization_method="estimated").fit(
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\statsmodels\tsa\holtwinters\model.py", line 1694, in __init__
    super().__init__(
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\statsmodels\tsa\holtwinters\model.py", line 243, in __init__
    raise ValueError(
ValueError: endog must be strictly positive when usingmultiplicative trend or seasonal components.
2023-03-16 11:53:20,828 automl_forecast modeling.py modeling fb_fit_predict INFO: fbprophet 데이터 준비
2023-03-16 11:53:20,829 automl_forecast modeling.py modeling fb_fit_predict INFO: fbprophet 모델링 시작
2023-03-16 13:06:03,354 automl_forecast modeling.py modeling fb_fit_predict ERROR: fbprophet 모델링 도중 문제가 발생하였습니다.
Traceback (most recent call last):
  File "C:\Users\dpapf\Desktop\automl_forecast\process\modeling.py", line 358, in fb_fit_predict
    fb.fit(fb_train[['y','ds','cap','floor']])
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\prophet\forecaster.py", line 1181, in fit
    self.params = self.stan_backend.fit(stan_init, dat, **kwargs)
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\prophet\models.py", line 96, in fit
    self.stan_fit = self.model.optimize(**args)
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\cmdstanpy\model.py", line 723, in optimize
    self._run_cmdstan(
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\cmdstanpy\model.py", line 1722, in _run_cmdstan
    line = proc.stdout.readline()
KeyboardInterrupt
2023-03-16 13:06:03,362 automl_forecast modeling.py modeling tft_fit_predict INFO: tft 데이터 준비
2023-03-16 13:06:03,362 automl_forecast modeling.py modeling tft_fit_predict INFO: tft 데이터 전처리
2023-03-16 13:06:03,396 automl_forecast modeling.py modeling tft_fit_predict INFO: tft dataloader 세팅
2023-03-16 13:06:04,518 automl_forecast modeling.py modeling tft_fit_predict INFO: tft learning rate 설정
2023-03-16 13:06:09,184 automl_forecast modeling.py modeling tft_fit_predict ERROR: tft learning rate 설정 도중 문제가 생겼습니다.
Traceback (most recent call last):
  File "C:\Users\dpapf\Desktop\automl_forecast\process\modeling.py", line 524, in tft_fit_predict
    res = trainer.tuner.lr_find(
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\pytorch_lightning\tuner\tuning.py", line 185, in lr_find
    result = self.trainer.tune(
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1099, in tune
    result = self.tuner._tune(model, scale_batch_size_kwargs=scale_batch_size_kwargs, lr_find_kwargs=lr_find_kwargs)
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\pytorch_lightning\tuner\tuning.py", line 53, in _tune
    result["lr_find"] = lr_find(self.trainer, model, **lr_find_kwargs)
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\pytorch_lightning\tuner\lr_finder.py", line 238, in lr_find
    trainer.tuner._run(model)
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\pytorch_lightning\tuner\tuning.py", line 63, in _run
    self.trainer._run(*args, **kwargs)
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1199, in _run
    self._dispatch()
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1289, in run_stage
    return self._run_train()
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1319, in _run_train
    self.fit_loop.run()
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\pytorch_lightning\loops\base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 234, in advance
    self.epoch_loop.run(data_fetcher)
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\pytorch_lightning\loops\base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\pytorch_lightning\loops\epoch\training_epoch_loop.py", line 156, in advance
    batch_idx, (batch, self.batch_progress.is_last_batch) = next(self._dataloader_iter)
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 203, in __next__
    return self.fetching_function()
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 270, in fetching_function
    self._fetch_next_batch()
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 300, in _fetch_next_batch
    batch = next(self.dataloader_iter)
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\pytorch_lightning\trainer\supporters.py", line 550, in __next__
    return self.request_next_batch(self.loader_iters)
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\pytorch_lightning\trainer\supporters.py", line 562, in request_next_batch
    return apply_to_collection(loader_iters, Iterator, next)
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\pytorch_lightning\utilities\apply_func.py", line 96, in apply_to_collection
    return function(data, *args, **kwargs)
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\torch\utils\data\dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\pytorch_forecasting\data\timeseries.py", line 1513, in __getitem__
    data_cont[:, self.reals.index("encoder_length")] = (
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\site-packages\pytorch_forecasting\data\timeseries.py", line 1027, in reals
    @property
KeyboardInterrupt
2023-03-16 13:06:09,256 automl_forecast modeling.py modeling tft_fit_predict INFO: tft 학습
2023-03-16 13:06:10,514 automl_forecast modeling.py modeling tft_fit_predict ERROR: tft 학습 도중 문제가 생겼습니다
Traceback (most recent call last):
  File "C:\Users\dpapf\Desktop\automl_forecast\process\modeling.py", line 582, in tft_fit_predict
    shutil.copyfile(best_model_path, tft_path)
  File "C:\Users\dpapf\anaconda3\envs\demand\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: ''
2023-03-16 13:06:10,524 automl_forecast modeling.py modeling tft_fit_predict INFO: 훈련, 검증 데이터 프레임 생성
2023-03-16 13:06:10,543 automl_forecast modeling.py modeling tft_fit_predict ERROR: 훈련, 검증 데이터 프레임 생성 도중 문제가 생겼습니다
Traceback (most recent call last):
  File "C:\Users\dpapf\Desktop\automl_forecast\process\modeling.py", line 596, in tft_fit_predict
    val_predictions = best_tft.predict(val_dataloader, mode="prediction", return_x=False)
UnboundLocalError: local variable 'best_tft' referenced before assignment
2023-03-16 13:06:10,544 automl_forecast modeling.py modeling tft_fit_predict INFO: 예측 데이터 프레임 생성
2023-03-16 13:06:10,582 automl_forecast modeling.py modeling tft_fit_predict ERROR: 예측 데이터 프레임 생성 도중 문제가 생겼습니다
Traceback (most recent call last):
  File "C:\Users\dpapf\Desktop\automl_forecast\process\modeling.py", line 648, in tft_fit_predict
    predictions = best_tft.predict(new_prediction_data, mode="prediction", return_x=False)
UnboundLocalError: local variable 'best_tft' referenced before assignment
